import type React from 'react'
import { createContext, useContext, useEffect, useMemo, useState } from 'react'

type Language = 'en' | 'es'

const LANG_KEY = 'mp3vine-lang'

const strings = {
  en: {
    // Topbar / nav
    home: 'Home',
    howItWorks: 'How it works',
    faq: 'FAQ',
    settings: 'Settings',
    languageLabel: 'Language',
    skipToContent: 'Skip to content',

    // Hero
    heroKicker: 'Direct download · no account · no queue',
    heroTitleA: 'Paste the link.',
    heroTitleB: 'Download the music.',
    heroSub: 'Drop in a Spotify URL or shortlink and save the files on your device. Tracks, albums, or full playlists with no desktop app or phone connection.',
    spotifyUrl: 'Spotify URL',
    search: 'Search ->',
    searching: 'Searching...',
    tryIt: 'Try it:',
    poweredBy: 'Powered by Spotify Web API',
    detectedTrack: 'Track detected',
    detectedAlbum: 'Album detected',
    detectedPlaylist: 'Playlist detected',
    detectedShortlink: 'Spotify shortlink detected',
    clearInput: 'Clear',
    inputPlaceholder: 'https://open.spotify.com/playlist/... or https://spotify.link/...',
    resolveError: 'Could not resolve URL',

    // Footer
    footerDisclaimer: 'Not affiliated with Spotify AB.',
    footerTerms: 'Terms',
    footerPrivacy: 'Privacy',
    footerAdmin: 'Admin',

    // Tutorial section
    tutorialKicker: 'Usage guide',
    tutorialTitle: 'Download music from Spotify links with more context and control',
    guideSections: 'Guide sections',
    sectionWhatItIs: 'What it is',
    sectionFeatures: 'Features',
    sectionGuide: 'Guide',
    sectionLimits: 'Limits',
    sectionFaq: 'FAQ',
    whatIsItKicker: 'What this page is',
    whatIsItTitle: 'A web tool for turning Spotify links into downloadable audio files',
    whatIsItP1: 'Mp3vine is a self-hosted page where you paste a Spotify link, resolve its tracks, and download audio as MP3, M4A, or OPUS from the browser. It works with individual tracks, albums, and playlists without a desktop app or cable-connected phone.',
    whatIsItP2: 'The page uses Spotify as the music information source: title, artist, album, cover art, duration, and playlist order. It then finds a compatible public audio source, usually on YouTube, and prepares the file with metadata so it is easier to organize in your player.',
    featuresKicker: 'Features',
    featuresTitle: 'What you can do here',
    quickGuideKicker: 'Quick guide',
    quickGuideTitle: 'How to use Mp3vine',
    step1Title: 'Copy a Spotify link',
    step1Body: 'Open Spotify web or the mobile app, find a track, album, or playlist, and use Share to copy the link.',
    step2Title: 'Paste it into search',
    step2Body: 'The page detects the link, loads cover art and tracks, and lets you filter by text or language before downloading.',
    step2Demo: 'Track / Album / Playlist OK',
    step3Title: 'Choose format and download',
    step3Body: 'Select MP3, M4A, or OPUS, choose quality, and download one track, the visible page, or a ZIP batch.',
    step3Demo: 'Download mp3 / 320 kbps / metadata included',
    limitsKicker: 'Limits',
    limitsTitle: 'What to know before downloading',
    faqTitle: 'Frequently asked questions',
    faqQ1: 'Do I need a Spotify account?',
    faqA1: 'You do not need to sign in as a user to paste links. The server does need free Spotify API credentials configured by the person hosting the page.',
    faqQ2: 'Where does the audio come from?',
    faqA2: 'Spotify is used for metadata and structure. Audio is resolved from public sources, usually YouTube, using artist, title, and duration checks.',
    faqQ3: 'Why can a track download the wrong audio?',
    faqA3: 'That can happen when YouTube returns a cover, remix, live video, or badly titled result. Manual review and retry with another source help with those cases.',
    faqQ4: 'How do large playlists work?',
    faqA4: 'The page loads 50 tracks per page. You can jump to a specific page, filter the visible results, and download in parts to avoid overloading the browser or server.',
    faqQ5: 'What does Other mean in the language filter?',
    faqA5: 'Other groups tracks with very short text, mixed language, instrumental names, proper nouns, or too little signal to classify confidently.',
    faqQ6: 'Which format and quality should I choose?',
    faqA6: 'MP3 at 320 kbps is the most compatible. M4A often balances quality and size. OPUS is efficient, but works best in modern players.',
    faqQ7: 'Can I use it from a phone?',
    faqA7: 'Yes. Open the page in your mobile browser, share or paste the Spotify link, and download the file directly to the device.',

    featureSpotifyLinksTitle: 'Spotify links',
    featureSpotifyLinksBody: 'Accepts tracks, albums, playlists, and Spotify shortlinks. The app identifies the link type and loads the main metadata before downloading.',
    featureMetadataTitle: 'Full metadata',
    featureMetadataBody: 'Uses Spotify for title, artist, album, cover art, duration, and track order. That information is embedded when the selected format supports it.',
    featureFormatsTitle: 'Flexible formats',
    featureFormatsBody: 'Choose MP3, M4A, or OPUS and adjust quality between 128, 192, and 320 kbps depending on compatibility, size, or efficiency.',
    featureLargeTitle: 'Large playlists',
    featureLargeBody: 'Playlists are shown in pages of 50 tracks so the browser and backend stay responsive even with long collections.',
    featureFiltersTitle: 'Useful filters',
    featureFiltersBody: 'Search by text and filter by detected language to review Spanish, English, Japanese, Korean, and other language groups more easily.',
    featureBatchTitle: 'Single or batch download',
    featureBatchBody: 'Download one track, the visible page, or generate a ZIP batch while keeping individual failures visible.',

    limit1: 'Spotify provides metadata; the audio is not downloaded directly from Spotify.',
    limit2: 'Availability depends on public audio sources found on YouTube.',
    limit3: 'Some matches can fail because of region locks, different durations, remixes, covers, or poorly titled videos.',
    limit4: 'Playlists are reviewed in pages of 50 tracks to keep the experience stable.',
    limit5: 'The server needs free Spotify API credentials to resolve albums, playlists, and tracks.',
    limit6: 'Final quality also depends on the original source, not only the selected bitrate.',

    // PlaylistCard
    plKindPlaylist: 'Spotify · Playlist',
    plKindAlbum: 'Spotify · Album',
    plKindTrack: 'Spotify · Track',
    plUntitled: 'Untitled',
    plTracksCount: (n: number) => `${n} tracks`,
    plShowing: (a: number, b: number) => `showing ${a}-${b}`,
    plMinutes: (m: number) => `${m} min`,
    plHourMinutes: (h: number, m: number) => `${h} h ${m} min`,
    plFormat: 'Format',
    plQuality: 'Quality',
    plDownloadAll: (n: number) => `⬇ Download all (${n})`,
    plDownloading: (done: number, total: number) => `⏳ Downloading... ${done}/${total}`,
    plZipGenerating: (done: number, total: number) => `Generating ZIP... ${done}/${total}`,
    plZipReady: '✓ ZIP ready',
    plZipDownload: '⬇ Download ZIP',
    plFilterInput: 'Filter title or artist',
    plLangFilter: 'Filter by language',
    plLangAll: 'All',
    plTracksShort: (n: number) => `${n} tracks`,
    plOfDownloaded: (_done: number, total: number) => `of ${total} downloaded`,
    plFailed: (n: number) => `${n} failed`,
    plParallel: 'Downloads run in parallel.',
    plRetryFailed: (n: number) => `↻ Retry failed (${n})`,
    plPageError: 'Could not load page',
    plLoadingResults: 'Loading results',
    plToastDownloaded: (n: number) => `${n} downloaded`,
    plToastDownloadedWithErrors: (done: number, errs: number) => `${done} downloaded · ${errs} failed`,
    plToastZipReady: 'ZIP ready',
    plToastZipFailed: 'ZIP generation failed',
    plToastZipNoIds: 'No tracks with Spotify IDs for the ZIP',
    plToastZipConnLost: 'Connection lost (ZIP)',
    plTracksLoaded: (n: number) => `${n} tracks loaded`,
    plTrackReady: 'Track ready to download',

    // TrackRow
    trDownload: '⬇ Download',
    trQueued: '⏳ Queued...',
    trDownloading: '⏳ Downloading...',
    trDownloaded: '✓ Downloaded',
    trRetry: '↻ Retry',
    trSearchManual: 'Search source manually',
    trSearchManualAria: 'Search YouTube source manually',
    trToastAdded: 'Track added to downloads',
    trToastReady: 'Download ready',
    trToastConnLost: 'Connection lost',
    trToastResolving: 'Resolving track...',
    trGeoRestricted: 'Region restricted - try a VPN',
    trError: 'Error',
    trConfirmFailed: 'Confirmation failed',

    // TrackPaginator
    pgLoading: (n: number) => `Loading page ${n}...`,
    pgPageOf: (cur: number, total: number, from: number, to: number, count: number) =>
      `Page ${cur} of ${total} · tracks ${from}-${to} of ${count}`,
    pgPrev: '← Previous',
    pgNext: 'Next →',
    pgPrevAria: 'Previous page',
    pgNextAria: 'Next page',
    pgGoAria: 'Go to page',
    pgJumpPlaceholder: 'Page',
    pgGo: 'Go',
    pgNavAria: 'Page navigation',

    // QuickTrackModal
    qmTrackDetected: 'Track detected',
    qmSingle: 'Single',
    qmFormat: 'Format',
    qmQuality: 'Quality',
    qmCancel: 'Cancel',
    qmDownloadNow: 'Download now',
    qmDownloading: 'Downloading...',
    qmToastLowConf: 'Low-confidence match - use the table flow to choose the source',
    qmToastFailed: 'Download failed',

    // ManualSearchModal
    msmKicker: 'Select YouTube source',
    msmClose: 'Close',
    msmSearchYT: 'Search YouTube',
    msmSearchPlaceholder: 'Search YouTube...',
    msmSearch: 'Search',
    msmEmpty: 'No results. Try another search.',
    msmUseThis: 'Use this',
    msmPasteLabel: 'Or paste a YouTube URL directly:',
    msmConfirm: 'Confirm',
    msmYoutubeUrl: 'YouTube URL',
    msmFailed: 'Search failed',

    // Settings
    setTitle: 'Settings',
    setSignOut: 'Sign out',
    setAdminLogin: 'Admin login',
    setAdminPassword: 'Admin password',
    setAdminPasswordPlaceholder: 'Enter admin password',
    setAdminPasswordHint: 'Set ADMIN_PASSWORD in the environment. Local fallback is admin.',
    setSignIn: 'Sign in',
    setSigningIn: 'Signing in...',
    setLoginOk: 'Admin session started',
    setLoginFailed: 'Login failed',
    setSignedOut: 'Signed out',
    setSignOutFailed: 'Sign out failed',
    setDefaultPwWarn: 'Default admin password is active.',
    setDefaultPwHint: ' Set ADMIN_PASSWORD before exposing this app.',
    setLoadError: 'Could not load settings:',
    setClientId: 'Spotify Client ID',
    setClientSecret: 'Spotify Client Secret',
    setCreateAtFree: 'Create it for free at',
    setDefaultFormat: 'Default format',
    setDefaultQuality: 'Default quality',
    setManualReviewTitle: 'Manual YouTube source review',
    setManualReviewHint: 'When enabled, low-confidence matches (<65%) show a modal so the admin can choose the source. When disabled, the best match downloads automatically.',
    setParallelDownloads: 'Parallel downloads',
    setParallelHint: 'Default is 3. Maximum is 5 to avoid saturating CPU and network.',
    setSave: 'Save changes',
    setSaving: 'Saving...',
    setSaved: 'Settings saved',
    setSaveFailed: 'Save failed',
    setVerify: 'Verify credentials',
    setChecking: 'Checking...',
    setSpotifyOk: 'Spotify connection OK',
    setSpotifyFail: (r: string) => `Not connected: ${r}`,
    setVerifyFailed: 'Verification failed',
    setUnknown: 'unknown',
    setSpotifyAppKicker: 'Spotify App',
    setConfigCreds: 'Configure credentials',
    setOpenDashboard: 'Open dashboard',
    setHelp1Title: 'Create the app',
    setHelp1Body: 'In the Spotify dashboard, use Create app and choose any internal name.',
    setHelp2Title: 'Copy the keys',
    setHelp2Body: 'Open Settings and paste the Client ID and Client Secret in the fields above.',
    setHelp3Title: 'Verify access',
    setHelp3Body: 'Save changes and run Verify credentials before resolving playlists.',
    setRedirectTitle: 'Redirect URI',
    setRedirectBody: 'If Spotify asks for a redirect URL, add this one for local development.',
    setBackend: 'Backend:',
    setSwaggerDocs: 'Swagger Docs',
    setSpotifyAppGuide: 'Spotify App setup guide',
  },
  es: {
    // Topbar / nav
    home: 'Inicio',
    howItWorks: 'Como funciona',
    faq: 'FAQ',
    settings: 'Configuracion',
    languageLabel: 'Idioma',
    skipToContent: 'Saltar al contenido',

    // Hero
    heroKicker: 'Descarga directa · sin cuenta · sin cola',
    heroTitleA: 'Pega el link.',
    heroTitleB: 'Descarga la musica.',
    heroSub: 'Pega una URL o shortlink de Spotify y guarda los archivos en tu dispositivo. Tracks, albumes o playlists completas sin app de escritorio ni conexion al telefono.',
    spotifyUrl: 'URL de Spotify',
    search: 'Buscar ->',
    searching: 'Buscando...',
    tryIt: 'Pruebalo:',
    poweredBy: 'Powered by Spotify Web API',
    detectedTrack: 'Track detectado',
    detectedAlbum: 'Album detectado',
    detectedPlaylist: 'Playlist detectada',
    detectedShortlink: 'Shortlink de Spotify detectado',
    clearInput: 'Limpiar',
    inputPlaceholder: 'https://open.spotify.com/playlist/... o https://spotify.link/...',
    resolveError: 'No se pudo resolver la URL',

    // Footer
    footerDisclaimer: 'Sin afiliación con Spotify AB.',
    footerTerms: 'Terminos',
    footerPrivacy: 'Privacidad',
    footerAdmin: 'Admin',

    // Tutorial section
    tutorialKicker: 'Guia de uso',
    tutorialTitle: 'Descarga musica de Spotify con mas contexto y control',
    guideSections: 'Secciones de la guia',
    sectionWhatItIs: 'Que es',
    sectionFeatures: 'Caracteristicas',
    sectionGuide: 'Guia',
    sectionLimits: 'Limites',
    sectionFaq: 'FAQ',
    whatIsItKicker: 'Que es esta pagina',
    whatIsItTitle: 'Una herramienta web para convertir links de Spotify en archivos de audio descargables',
    whatIsItP1: 'Mp3vine es una pagina autoalojada donde pegas un link de Spotify, resuelves sus tracks y descargas el audio como MP3, M4A o OPUS desde el navegador. Funciona con tracks individuales, albumes y playlists sin app de escritorio ni telefono conectado por cable.',
    whatIsItP2: 'La pagina usa Spotify como fuente de informacion musical: titulo, artista, album, portada, duracion y orden de la playlist. Luego encuentra una fuente publica de audio compatible, normalmente en YouTube, y prepara el archivo con metadatos para que sea mas facil organizarlo en tu reproductor.',
    featuresKicker: 'Caracteristicas',
    featuresTitle: 'Lo que puedes hacer aqui',
    quickGuideKicker: 'Guia rapida',
    quickGuideTitle: 'Como usar Mp3vine',
    step1Title: 'Copia un link de Spotify',
    step1Body: 'Abre Spotify web o la app movil, busca un track, album o playlist y usa Compartir para copiar el link.',
    step2Title: 'Pegalo en la busqueda',
    step2Body: 'La pagina detecta el link, carga portada y tracks y te deja filtrar por texto o idioma antes de descargar.',
    step2Demo: 'Track / Album / Playlist OK',
    step3Title: 'Elige formato y descarga',
    step3Body: 'Selecciona MP3, M4A u OPUS, elige calidad y descarga un track, la pagina visible o un ZIP por lote.',
    step3Demo: 'Descarga mp3 / 320 kbps / metadatos incluidos',
    limitsKicker: 'Limites',
    limitsTitle: 'Que debes saber antes de descargar',
    faqTitle: 'Preguntas frecuentes',
    faqQ1: '¿Necesito una cuenta de Spotify?',
    faqA1: 'No necesitas iniciar sesion como usuario para pegar links. El servidor si necesita credenciales gratuitas de la API de Spotify configuradas por quien hospeda la pagina.',
    faqQ2: '¿De donde sale el audio?',
    faqA2: 'Spotify se usa para metadatos y estructura. El audio se resuelve desde fuentes publicas, normalmente YouTube, comparando artista, titulo y duracion.',
    faqQ3: '¿Por que un track puede descargar el audio equivocado?',
    faqA3: 'Puede ocurrir cuando YouTube devuelve un cover, remix, video en vivo o un resultado mal titulado. La revision manual y reintentar con otra fuente ayudan en esos casos.',
    faqQ4: '¿Como funcionan las playlists grandes?',
    faqA4: 'La pagina carga 50 tracks por pagina. Puedes saltar a una pagina especifica, filtrar los resultados visibles y descargar por partes para no saturar el navegador ni el servidor.',
    faqQ5: '¿Que significa Other en el filtro de idioma?',
    faqA5: 'Other agrupa tracks con texto muy corto, idioma mixto, nombres instrumentales, nombres propios o poca señal para clasificarlos con confianza.',
    faqQ6: '¿Que formato y calidad debo elegir?',
    faqA6: 'MP3 a 320 kbps es el mas compatible. M4A suele balancear calidad y tamaño. OPUS es eficiente pero funciona mejor en reproductores modernos.',
    faqQ7: '¿Lo puedo usar desde el telefono?',
    faqA7: 'Si. Abre la pagina en el navegador movil, comparte o pega el link de Spotify y descarga el archivo directo al dispositivo.',

    featureSpotifyLinksTitle: 'Links de Spotify',
    featureSpotifyLinksBody: 'Acepta tracks, albumes, playlists y shortlinks de Spotify. La app identifica el tipo de link y carga los metadatos principales antes de descargar.',
    featureMetadataTitle: 'Metadatos completos',
    featureMetadataBody: 'Usa Spotify para titulo, artista, album, portada, duracion y orden de track. Esa informacion se embebe cuando el formato lo soporta.',
    featureFormatsTitle: 'Formatos flexibles',
    featureFormatsBody: 'Elige MP3, M4A u OPUS y ajusta calidad entre 128, 192 y 320 kbps segun compatibilidad, tamaño o eficiencia.',
    featureLargeTitle: 'Playlists grandes',
    featureLargeBody: 'Las playlists se muestran en paginas de 50 tracks para que navegador y backend sigan respondiendo aun con colecciones largas.',
    featureFiltersTitle: 'Filtros utiles',
    featureFiltersBody: 'Busca por texto y filtra por idioma detectado para revisar español, ingles, japones, coreano y otros grupos de idiomas mas facil.',
    featureBatchTitle: 'Descarga individual o por lote',
    featureBatchBody: 'Descarga un track, la pagina visible o genera un ZIP por lote manteniendo visibles los fallos individuales.',

    limit1: 'Spotify entrega los metadatos; el audio no se descarga directo de Spotify.',
    limit2: 'La disponibilidad depende de las fuentes publicas de audio encontradas en YouTube.',
    limit3: 'Algunos matches pueden fallar por bloqueos regionales, duraciones distintas, remixes, covers o videos mal titulados.',
    limit4: 'Las playlists se revisan en paginas de 50 tracks para mantener una experiencia estable.',
    limit5: 'El servidor necesita credenciales gratuitas de la API de Spotify para resolver albumes, playlists y tracks.',
    limit6: 'La calidad final tambien depende del origen, no solo del bitrate seleccionado.',

    // PlaylistCard
    plKindPlaylist: 'Spotify · Playlist',
    plKindAlbum: 'Spotify · Album',
    plKindTrack: 'Spotify · Track',
    plUntitled: 'Sin titulo',
    plTracksCount: (n: number) => `${n} tracks`,
    plShowing: (a: number, b: number) => `mostrando ${a}-${b}`,
    plMinutes: (m: number) => `${m} min`,
    plHourMinutes: (h: number, m: number) => `${h} h ${m} min`,
    plFormat: 'Formato',
    plQuality: 'Calidad',
    plDownloadAll: (n: number) => `⬇ Descargar todo (${n})`,
    plDownloading: (done: number, total: number) => `⏳ Descargando... ${done}/${total}`,
    plZipGenerating: (done: number, total: number) => `Generando ZIP... ${done}/${total}`,
    plZipReady: '✓ ZIP listo',
    plZipDownload: '⬇ Descargar ZIP',
    plFilterInput: 'Filtra por titulo o artista',
    plLangFilter: 'Filtrar por idioma',
    plLangAll: 'Todos',
    plTracksShort: (n: number) => `${n} tracks`,
    plOfDownloaded: (_done: number, total: number) => `de ${total} descargados`,
    plFailed: (n: number) => `${n} con error`,
    plParallel: 'Las descargas corren en paralelo.',
    plRetryFailed: (n: number) => `↻ Reintentar fallidas (${n})`,
    plPageError: 'No se pudo cargar la pagina',
    plLoadingResults: 'Cargando resultados',
    plToastDownloaded: (n: number) => `${n} descargados`,
    plToastDownloadedWithErrors: (done: number, errs: number) => `${done} descargados · ${errs} con error`,
    plToastZipReady: 'ZIP listo',
    plToastZipFailed: 'Fallo al generar el ZIP',
    plToastZipNoIds: 'No hay tracks con IDs de Spotify para el ZIP',
    plToastZipConnLost: 'Conexion perdida (ZIP)',
    plTracksLoaded: (n: number) => `${n} tracks cargados`,
    plTrackReady: 'Track listo para descargar',

    // TrackRow
    trDownload: '⬇ Descargar',
    trQueued: '⏳ En cola...',
    trDownloading: '⏳ Descargando...',
    trDownloaded: '✓ Descargado',
    trRetry: '↻ Reintentar',
    trSearchManual: 'Buscar la fuente manualmente',
    trSearchManualAria: 'Buscar la fuente de YouTube manualmente',
    trToastAdded: 'Track añadido a descargas',
    trToastReady: 'Descarga lista',
    trToastConnLost: 'Conexion perdida',
    trToastResolving: 'Resolviendo track...',
    trGeoRestricted: 'Restringido por region - prueba una VPN',
    trError: 'Error',
    trConfirmFailed: 'Confirmacion fallida',

    // TrackPaginator
    pgLoading: (n: number) => `Cargando pagina ${n}...`,
    pgPageOf: (cur: number, total: number, from: number, to: number, count: number) =>
      `Pagina ${cur} de ${total} · tracks ${from}-${to} de ${count}`,
    pgPrev: '← Anterior',
    pgNext: 'Siguiente →',
    pgPrevAria: 'Pagina anterior',
    pgNextAria: 'Pagina siguiente',
    pgGoAria: 'Ir a la pagina',
    pgJumpPlaceholder: 'Pagina',
    pgGo: 'Ir',
    pgNavAria: 'Navegacion de paginas',

    // QuickTrackModal
    qmTrackDetected: 'Track detectado',
    qmSingle: 'Single',
    qmFormat: 'Formato',
    qmQuality: 'Calidad',
    qmCancel: 'Cancelar',
    qmDownloadNow: 'Descargar ahora',
    qmDownloading: 'Descargando...',
    qmToastLowConf: 'Match de baja confianza - usa el flujo de tabla para elegir fuente',
    qmToastFailed: 'Descarga fallida',

    // ManualSearchModal
    msmKicker: 'Elegir fuente de YouTube',
    msmClose: 'Cerrar',
    msmSearchYT: 'Buscar en YouTube',
    msmSearchPlaceholder: 'Buscar en YouTube...',
    msmSearch: 'Buscar',
    msmEmpty: 'Sin resultados. Prueba otra busqueda.',
    msmUseThis: 'Usar este',
    msmPasteLabel: 'O pega un URL de YouTube directamente:',
    msmConfirm: 'Confirmar',
    msmYoutubeUrl: 'URL de YouTube',
    msmFailed: 'Busqueda fallida',

    // Settings
    setTitle: 'Configuracion',
    setSignOut: 'Cerrar sesion',
    setAdminLogin: 'Login de administrador',
    setAdminPassword: 'Contraseña de administrador',
    setAdminPasswordPlaceholder: 'Introduce la contraseña de administrador',
    setAdminPasswordHint: 'Configura ADMIN_PASSWORD en el entorno. Por defecto local es admin.',
    setSignIn: 'Entrar',
    setSigningIn: 'Entrando...',
    setLoginOk: 'Sesion de administrador iniciada',
    setLoginFailed: 'Login fallido',
    setSignedOut: 'Sesion cerrada',
    setSignOutFailed: 'Error al cerrar sesion',
    setDefaultPwWarn: 'La contraseña de administrador por defecto esta activa.',
    setDefaultPwHint: ' Configura ADMIN_PASSWORD antes de exponer esta app.',
    setLoadError: 'No se pudo cargar la configuracion:',
    setClientId: 'Client ID de Spotify',
    setClientSecret: 'Client Secret de Spotify',
    setCreateAtFree: 'Crealo gratis en',
    setDefaultFormat: 'Formato por defecto',
    setDefaultQuality: 'Calidad por defecto',
    setManualReviewTitle: 'Revision manual de fuente YouTube',
    setManualReviewHint: 'Cuando esta activo, los matches de baja confianza (<65%) muestran un modal para que el admin elija la fuente. Cuando esta desactivado, se descarga automaticamente el mejor match.',
    setParallelDownloads: 'Descargas en paralelo',
    setParallelHint: 'Por defecto 3. Maximo 5 para no saturar CPU y red.',
    setSave: 'Guardar cambios',
    setSaving: 'Guardando...',
    setSaved: 'Configuracion guardada',
    setSaveFailed: 'Error al guardar',
    setVerify: 'Verificar credenciales',
    setChecking: 'Verificando...',
    setSpotifyOk: 'Conexion con Spotify OK',
    setSpotifyFail: (r: string) => `No conectado: ${r}`,
    setVerifyFailed: 'Verificacion fallida',
    setUnknown: 'desconocido',
    setSpotifyAppKicker: 'App de Spotify',
    setConfigCreds: 'Configurar credenciales',
    setOpenDashboard: 'Abrir dashboard',
    setHelp1Title: 'Crea la app',
    setHelp1Body: 'En el dashboard de Spotify, usa Crear app y elige cualquier nombre interno.',
    setHelp2Title: 'Copia las claves',
    setHelp2Body: 'Abre Configuracion y pega el Client ID y Client Secret en los campos de arriba.',
    setHelp3Title: 'Verifica el acceso',
    setHelp3Body: 'Guarda cambios y ejecuta Verificar credenciales antes de resolver playlists.',
    setRedirectTitle: 'Redirect URI',
    setRedirectBody: 'Si Spotify pide una URL de redirect, añade esta para desarrollo local.',
    setBackend: 'Backend:',
    setSwaggerDocs: 'Swagger Docs',
    setSpotifyAppGuide: 'Guia de configuracion de la app de Spotify',
  },
} as const

type StringKey = keyof typeof strings.en

type PreferencesContextValue = {
  language: Language
  setLanguage: (language: Language) => void
  t: <K extends StringKey>(key: K) => (typeof strings.en)[K]
}

const PreferencesContext = createContext<PreferencesContextValue | null>(null)

function initialLanguage(): Language {
  const stored = window.localStorage.getItem(LANG_KEY)
  return stored === 'es' ? 'es' : 'en'
}

export function PreferencesProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>(initialLanguage)

  const setLanguage = (next: Language) => {
    setLanguageState(next)
    window.localStorage.setItem(LANG_KEY, next)
  }

  useEffect(() => {
    document.documentElement.lang = language
  }, [language])

  const value = useMemo<PreferencesContextValue>(() => ({
    language,
    setLanguage,
    t: <K extends StringKey>(key: K) => strings[language][key] as (typeof strings.en)[K],
  }), [language])

  return (
    <PreferencesContext.Provider value={value}>
      {children}
    </PreferencesContext.Provider>
  )
}

export function usePreferences() {
  const ctx = useContext(PreferencesContext)
  if (!ctx) throw new Error('usePreferences must be used inside PreferencesProvider')
  return ctx
}
