import { usePreferences } from '../preferences'

export function PrivacyView() {
  const { language } = usePreferences()
  return (
    <div className="legal-wrap">
      {language === 'es' ? <PrivacyES /> : <PrivacyEN />}
    </div>
  )
}

function PrivacyEN() {
  return (
    <article>
      <h1>Privacy Policy</h1>
      <p className="legal-meta">Last updated: June 2026</p>

      <h2>1. What we collect</h2>
      <p>
        Mp3vine is designed to collect as little data as possible. The
        instance you are using does not ask for an account, does not run
        third-party analytics, and does not embed advertising trackers.
      </p>
      <p>The only data that is processed is:</p>
      <ul>
        <li>
          <strong>The Spotify link you paste.</strong> It is sent to the
          backend to read its public metadata (title, artist, album, cover,
          duration). It is not stored after the page is closed.
        </li>
        <li>
          <strong>An admin session cookie</strong> (HTTP-only, signed) that is
          created only after a successful admin login. It expires
          automatically and contains no personal information.
        </li>
        <li>
          <strong>Server logs</strong> generated by the host (FastAPI / reverse
          proxy). These may include IP address and user agent, kept for
          short-term debugging only.
        </li>
      </ul>

      <h2>2. What we do not collect</h2>
      <ul>
        <li>No Spotify account credentials. The app uses your server-side API key, not your login.</li>
        <li>No payment information.</li>
        <li>No advertising or social-media tracking pixels.</li>
        <li>No location tracking.</li>
      </ul>

      <h2>3. Downloaded files</h2>
      <p>
        Files are written to a temporary directory on the server, streamed to
        your browser, and removed automatically after a short period. The
        operator of the instance may configure that period; consult them for
        the exact retention window.
      </p>

      <h2>4. Cookies and local storage</h2>
      <p>
        The site uses local storage to remember your interface preferences
        (language, theme, last visited page) and an HTTP-only cookie only after
        admin login. No cookies are used for tracking.
      </p>

      <h2>5. Third-party services</h2>
      <p>
        The backend contacts the Spotify Web API to resolve metadata and
        contacts public audio sources to download the requested track. These
        third parties have their own privacy policies and are responsible for
        the data they receive (typically: the public ID of the requested
        resource and the server&apos;s IP).
      </p>

      <h2>6. Your rights</h2>
      <p>
        Because the operator of the instance you are using controls the server,
        any request related to your data (access, deletion, correction) should
        be addressed to that operator.
      </p>

      <h2>7. Changes</h2>
      <p>
        This policy may be updated without notice. The version published on
        this page is the one currently in force.
      </p>
    </article>
  )
}

function PrivacyES() {
  return (
    <article>
      <h1>Política de privacidad</h1>
      <p className="legal-meta">Última actualización: junio de 2026</p>

      <h2>1. Qué recopilamos</h2>
      <p>
        Mp3vine está diseñada para recopilar la menor cantidad posible de
        datos. La instancia que estás usando no pide cuenta, no usa analítica
        de terceros y no incluye pixeles de publicidad.
      </p>
      <p>Los únicos datos que se procesan son:</p>
      <ul>
        <li>
          <strong>El enlace de Spotify que pegas.</strong> Se envía al backend
          para leer sus metadatos públicos (título, artista, álbum, portada,
          duración). No se almacena tras cerrar la página.
        </li>
        <li>
          <strong>Una cookie de sesión de administrador</strong> (HTTP-only,
          firmada) que solo se crea tras un inicio de sesión correcto. Expira
          automáticamente y no contiene información personal.
        </li>
        <li>
          <strong>Logs del servidor</strong> generados por el host (FastAPI /
          reverse proxy). Pueden incluir IP y user agent, y se conservan solo
          el tiempo necesario para depuración.
        </li>
      </ul>

      <h2>2. Qué no recopilamos</h2>
      <ul>
        <li>Ninguna credencial de tu cuenta de Spotify. La app usa la API key del servidor, no tu login.</li>
        <li>Ningún dato de pago.</li>
        <li>Ningún pixel de publicidad ni de redes sociales.</li>
        <li>Ningún rastreo de ubicación.</li>
      </ul>

      <h2>3. Archivos descargados</h2>
      <p>
        Los archivos se escriben en un directorio temporal del servidor, se
        envían al navegador y se eliminan automáticamente tras un periodo
        breve. El operador de la instancia puede configurar ese periodo;
        consulta con él la ventana exacta de retención.
      </p>

      <h2>4. Cookies y almacenamiento local</h2>
      <p>
        El sitio usa almacenamiento local para recordar tus preferencias de
        interfaz (idioma, tema, última página visitada) y una cookie HTTP-only
        únicamente tras el login de administrador. No se usan cookies de
        seguimiento.
      </p>

      <h2>5. Servicios de terceros</h2>
      <p>
        El backend contacta con la API web de Spotify para resolver metadatos y
        con fuentes públicas de audio para descargar la pista solicitada. Esos
        terceros tienen sus propias políticas de privacidad y son responsables
        de los datos que reciben (normalmente: el ID público del recurso
        pedido y la IP del servidor).
      </p>

      <h2>6. Tus derechos</h2>
      <p>
        Como el operador de la instancia que usas controla el servidor,
        cualquier solicitud relacionada con tus datos (acceso, supresión,
        rectificación) debe dirigirse a ese operador.
      </p>

      <h2>7. Cambios</h2>
      <p>
        Esta política puede actualizarse sin previo aviso. La versión publicada
        en esta página es la que está en vigor.
      </p>
    </article>
  )
}
